spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ${MONGODB_DATABASE}

  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: ${OAUTH2_NAVER_CLIENT_ID}
            clientSecret: ${OAUTH2_NAVER_CLIENT_SECRET}
            redirectUri: ${OAUTH2_NAVER_REDIRECT_URI}


app:
  cors:
    allowed-origins: http://localhost:3000