spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET}
      region:
        static: ap-northeast-2
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@ec2-3-35-87-46.ap-northeast-2.compute.amazonaws.com:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: Comission_Platform

  jwt:
    secret: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: ${OAUTH2_NAVER_CLIENT_ID}
            clientSecret: ${OAUTH2_NAVER_CLIENT_SECRET}
            redirectUri: ${OAUTH2_NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: name,email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
