services:
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - LC_ALL=C.UTF-8
    command: [--auth]
    volumes:
      - testmongo-volume:/data/db
    networks:
      - test_network

  spring-boot-app:
    image: dongick/gitaction-test
    container_name: gitaction-test
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - test_network

networks:
  test_network:

volumes:
  testmongo-volume:
    external: true