services:
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    command: [--auth]
    volumes:
      - testmongo-volume:/data/db
    networks:
      - test_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    volumes:
      - testmysql-volume:/var/lib/mysql
    networks:
      - test_network

  spring-boot-app:
    image: dongick/gitaction-test
    container_name: gitaction-test
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
      - mysql
    networks:
      - test_network

networks:
  test_network:

volumes:
  testmongo-volume:
    external: true
  testmysql-volume:
    external: true