version: '3.8'

services:
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - testmongo-volume:/data/db
    networks:
      - test_network

  spring-boot-app:
    image: dongick/gitaction-test
    container_name: gitaction-test
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - OAUTH2_NAVER_CLIENT_ID=${OAUTH2_NAVER_CLIENT_ID}
      - OAUTH2_NAVER_CLIENT_SECRET=${OAUTH2_NAVER_CLIENT_SECRET}
      - OAUTH2_NAVER_REDIRECT_URI=${OAUTH2_NAVER_REDIRECT_URI}
    depends_on:
      - mongodb
    networks:
      - test_network

networks:
  test_network:

volumes:
  testmongo-volume:
    external: true